---
#- name: Initialize the Cluster
#  command: kubeadm init
#  when: "'k8s-controllers' in group_names"
#  become: yes

- name: Create .kube folder
  file:
    dest: "{{ home }}/.kube"
    mode: directory
    owner: "{{ k8s_user }}"
    group: "{{ k8s_user}}"

#   mkdir -p $HOME/.kube
#  sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#  sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Run kubeadm token create --print-join-command and register output
  shell: kubeadm token create --print-join-command
  register: join_command_output
  when: "'k8s-controllers' in group_names"

- name: Debug the output of kubeadm join command
  debug:
    msg: "{{ join_command_output.stdout }}"
  when: "'k8s-controllers' in group_names"
